from __future__ import annotations

import tempfile
import textwrap
import unittest
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from witup_llm.config import load_config
from witup_llm.domain import build_benchmark_scenarios
from witup_llm.llm import LLMResponse
from witup_llm.metrics import MetricRunner
from witup_llm.metrics import MetricRuntimeContext
from witup_llm.models import MetricResult
from witup_llm.pipelines import PipelineService


JAVA_SOURCE = """
package com.example.pipeline;

public class TransferService {
  public void transfer(int amount) {
    if (amount <= 0) {
      throw new IllegalArgumentException("amount");
    }
  }
}
"""


class FakeLLMClient:
    def complete_json(self, model, system_prompt: str, user_prompt: str) -> LLMResponse:
        if "Analyse the method below" in user_prompt:
            return LLMResponse(
                payload={
                    "method_summary": "Validates transfer amount before processing.",
                    "expaths": [
                        {
                            "path_id": f"{model.key}-path",
                            "exception_type": "IllegalArgumentException",
                            "trigger": "Amount is zero or negative.",
                            "guard_conditions": ["amount <= 0"],
                            "confidence": 0.92,
                            "evidence": ["throw new IllegalArgumentException"],
                        }
                    ],
                },
                raw_text='{"method_summary":"ok","expaths":[]}',
            )
        if "Generate unit tests for container" in user_prompt:
            return LLMResponse(
                payload={
                    "strategy_summary": f"Generate boundary tests with model {model.key}.",
                    "test_files": [
                        {
                            "relative_path": "com/example/pipeline/TransferServiceTest.java",
                            "content": (
                                "package com.example.pipeline;\n\n"
                                "class TransferServiceTest {\n"
                                "  // generated by model\n"
                                "}\n"
                            ),
                            "covered_method_ids": ["com.example.pipeline.TransferService:transfer:4"],
                            "notes": "Covers invalid amount path.",
                        }
                    ],
                },
                raw_text='{"strategy_summary":"ok","test_files":[]}',
            )
        return LLMResponse(
            payload={
                "score": 88 if model.key == "judge" else 70,
                "verdict": f"Tests generated with {model.key} look effective.",
                "strengths": ["Clear negative-path assertions."],
                "weaknesses": ["Needs more integration context."],
                "risks": ["Might miss side effects."],
                "recommended_next_actions": ["Add more happy-path coverage."],
            },
            raw_text='{"score":88}',
        )


class FakeMetricRunner(MetricRunner):
    def run_all(self, metrics, context: MetricRuntimeContext):
        score = 82.0 if context.model_key == "model-b" else 73.0
        return [
            MetricResult(
                name="coverage",
                kind="coverage",
                command="fake",
                success=True,
                exit_code=0,
                stdout="coverage 82%",
                stderr="",
                numeric_value=score,
                normalized_score=score,
                weight=1.0,
                description="statement coverage",
            )
        ]


class PipelineServiceTest(unittest.TestCase):
    def test_run_full_pipeline(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = prepare_project(Path(tmp_dir))
            config = load_config(root / "witup.toml")
            service = PipelineService(llm_client=FakeLLMClient(), metric_runner=FakeMetricRunner())

            result = service.run(
                config,
                analysis_model_key="model-a",
                generation_model_key="model-a",
                judge_model_key="judge",
            )

            analysis_report = result["analysis_report"]
            generation_report = result["generation_report"]
            evaluation_report = result["evaluation_report"]

            self.assertEqual(1, analysis_report.total_methods)
            self.assertEqual(1, len(analysis_report.analyses[0].expaths))
            self.assertEqual(1, len(generation_report.test_files))
            self.assertAlmostEqual(73.0, evaluation_report.metric_score)
            self.assertAlmostEqual(80.5, evaluation_report.combined_score)
            self.assertTrue((result["workspace"] / "generated-tests").exists())

    def test_benchmark_ranks_models(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = prepare_project(Path(tmp_dir))
            config = load_config(root / "witup.toml")
            service = PipelineService(llm_client=FakeLLMClient(), metric_runner=FakeMetricRunner())

            report, benchmark_path = service.benchmark(
                config,
                scenarios=build_benchmark_scenarios(model_keys=["model-a", "model-b"]),
                judge_model_key=None,
            )

            self.assertTrue(benchmark_path.exists())
            self.assertEqual("model-b", report.entries[0].generation_model_key)
            self.assertEqual(1, report.entries[0].rank)
            self.assertEqual("model-a", report.entries[1].generation_model_key)

    def test_benchmark_supports_matrix_of_models(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = prepare_project(Path(tmp_dir))
            config = load_config(root / "witup.toml")
            service = PipelineService(llm_client=FakeLLMClient(), metric_runner=FakeMetricRunner())

            report, benchmark_path = service.benchmark(
                config,
                scenarios=build_benchmark_scenarios(
                    analysis_model_keys=["model-a"],
                    generation_model_keys=["model-a", "model-b"],
                ),
                judge_model_key=None,
            )

            self.assertTrue(benchmark_path.exists())
            self.assertEqual(2, len(report.entries))
            self.assertEqual("model-a", report.entries[0].analysis_model_key)
            self.assertEqual("model-b", report.entries[0].generation_model_key)
            self.assertEqual(1, report.entries[0].rank)
            markdown = (benchmark_path.parent / "benchmark.md").read_text(encoding="utf-8")
            self.assertIn("model-a->model-b", markdown)


def prepare_project(root: Path) -> Path:
    source_path = root / "src" / "main" / "java" / "com" / "example" / "pipeline" / "TransferService.java"
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text(textwrap.dedent(JAVA_SOURCE).strip() + "\n", encoding="utf-8")
    (root / "README.md").write_text("A payment transfer service.", encoding="utf-8")
    (root / "witup.toml").write_text(
        textwrap.dedent(
            """
            [project]
            root = "."
            language = "java"
            include = ["src/main/java"]
            overview_file = "README.md"
            test_framework = "junit5"

            [pipeline]
            output_dir = "generated"
            save_prompts = true
            judge_model = "judge"

            [models.model-a]
            provider = "ollama"
            model = "model-a"
            base_url = "http://localhost:11434"

            [models.model-b]
            provider = "ollama"
            model = "model-b"
            base_url = "http://localhost:11434"

            [models.judge]
            provider = "ollama"
            model = "judge"
            base_url = "http://localhost:11434"

            [[metrics]]
            name = "coverage"
            kind = "coverage"
            command = "echo 73"
            value_regex = "(\\\\d+)"
            """
        ).strip()
        + "\n",
        encoding="utf-8",
    )
    return root


if __name__ == "__main__":
    unittest.main()
